### ISSUE TITLE
How to form a TOP select statement ?

### ISSUE THREAD

**Issue by mallim** [pnowy/NativeCriteria#23]
NativeCriteria version = 2.0

Intend to form a statement = select top 100 col1, col2 from tableA

Using 

````
NativeExps.customSql( "TOP 100")
````

or 

````
NativeExps.sql( "TOP 100" )
````

will result in an extra comma:

````
select top 100, col1, col2 from tableA
````

**Comment by pnowy** [comment]
Hello,

for TOP & LIMIT expression please use the the ```setLimit()``` and ```setOffset``` methods from NativeCriteria class.

This should be used in this way because various databases use different query for this (especially Oracle which needs the subquery for retrieve top rows).

You could see the example here:

**H2:** SELECT a.* FROM ADDRESS a ORDER BY a.id ASC limit ?
**SQL SERVER:** SELECT top 3 a.* FROM ADDRESS a ORDER BY a.id ASC

I've added the example test (see SelectTopRowsQueryTest on test module).

Regarding the problem with comma I will create new task and take care that for custom SQL no additional comma will be used.
